/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as taskManagerSol from "./TaskManager.sol";
export type { taskManagerSol };
import type * as verificationContractSol from "./VerificationContract.sol";
export type { verificationContractSol };
export type { AntiFraud } from "./AntiFraud";
export type { BountyPool } from "./BountyPool";
export type { ReputationContract } from "./ReputationContract";
