/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReputationContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BADGE_SUCCESS_RATE_THRESHOLD"
      | "BADGE_TASK_THRESHOLD"
      | "BASIS_POINTS"
      | "HIGH_REPUTATION_THRESHOLD"
      | "INITIAL_REPUTATION"
      | "MAX_REPUTATION"
      | "MIN_REPUTATION"
      | "REPUTATION_DECREASE"
      | "REPUTATION_INCREASE"
      | "REPUTATION_MULTIPLIER_PERCENTAGE"
      | "getCategoryStats"
      | "getReputationData"
      | "getReputationMultiplier"
      | "getReputationScore"
      | "getSuccessRate"
      | "getVerificationAccuracy"
      | "hasCategoryBadge"
      | "hasPriorityAccess"
      | "initializeReputation"
      | "owner"
      | "renounceOwnership"
      | "setTaskManager"
      | "setVerificationContract"
      | "taskManagerAddress"
      | "transferOwnership"
      | "updateVerifierReputation"
      | "updateWorkerReputation"
      | "updateWorkerReputationWithCategory"
      | "verificationContractAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CategoryBadgeAwarded"
      | "OwnershipTransferred"
      | "ReputationInitialized"
      | "TaskManagerUpdated"
      | "VerificationContractUpdated"
      | "VerifierReputationUpdated"
      | "WorkerReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BADGE_SUCCESS_RATE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BADGE_TASK_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HIGH_REPUTATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_DECREASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_INCREASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPUTATION_MULTIPLIER_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCategoryStats",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationMultiplier",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSuccessRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationAccuracy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCategoryBadge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPriorityAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTaskManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskManagerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVerifierReputation",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWorkerReputation",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWorkerReputationWithCategory",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationContractAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BADGE_SUCCESS_RATE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BADGE_TASK_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HIGH_REPUTATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_DECREASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_INCREASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPUTATION_MULTIPLIER_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCategoryStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSuccessRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationAccuracy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCategoryBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPriorityAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTaskManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVerifierReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWorkerReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWorkerReputationWithCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationContractAddress",
    data: BytesLike
  ): Result;
}

export namespace CategoryBadgeAwardedEvent {
  export type InputTuple = [worker: AddressLike, category: BigNumberish];
  export type OutputTuple = [worker: string, category: bigint];
  export interface OutputObject {
    worker: string;
    category: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationInitializedEvent {
  export type InputTuple = [user: AddressLike, initialScore: BigNumberish];
  export type OutputTuple = [user: string, initialScore: bigint];
  export interface OutputObject {
    user: string;
    initialScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskManagerUpdatedEvent {
  export type InputTuple = [newContract: AddressLike];
  export type OutputTuple = [newContract: string];
  export interface OutputObject {
    newContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationContractUpdatedEvent {
  export type InputTuple = [newContract: AddressLike];
  export type OutputTuple = [newContract: string];
  export interface OutputObject {
    newContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierReputationUpdatedEvent {
  export type InputTuple = [
    verifier: AddressLike,
    accurate: boolean,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    verifier: string,
    accurate: boolean,
    newScore: bigint
  ];
  export interface OutputObject {
    verifier: string;
    accurate: boolean;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkerReputationUpdatedEvent {
  export type InputTuple = [
    worker: AddressLike,
    successful: boolean,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    worker: string,
    successful: boolean,
    newScore: bigint
  ];
  export interface OutputObject {
    worker: string;
    successful: boolean;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationContract extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationContract;
  waitForDeployment(): Promise<this>;

  interface: ReputationContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BADGE_SUCCESS_RATE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  BADGE_TASK_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  HIGH_REPUTATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  INITIAL_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MAX_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MIN_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_DECREASE: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_INCREASE: TypedContractMethod<[], [bigint], "view">;

  REPUTATION_MULTIPLIER_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  getCategoryStats: TypedContractMethod<
    [user: AddressLike, category: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        successCount: bigint;
        totalCount: bigint;
        hasBadge: boolean;
        successRate: bigint;
      }
    ],
    "view"
  >;

  getReputationData: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        tasksCompleted: bigint;
        tasksRejected: bigint;
        verificationsPerformed: bigint;
        accurateVerifications: bigint;
      }
    ],
    "view"
  >;

  getReputationMultiplier: TypedContractMethod<
    [user: AddressLike, category: BigNumberish],
    [bigint],
    "view"
  >;

  getReputationScore: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getSuccessRate: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getVerificationAccuracy: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  hasCategoryBadge: TypedContractMethod<
    [user: AddressLike, category: BigNumberish],
    [boolean],
    "view"
  >;

  hasPriorityAccess: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  initializeReputation: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTaskManager: TypedContractMethod<
    [_taskManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerificationContract: TypedContractMethod<
    [_verificationContract: AddressLike],
    [void],
    "nonpayable"
  >;

  taskManagerAddress: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateVerifierReputation: TypedContractMethod<
    [verifier: AddressLike, accurateVote: boolean],
    [void],
    "nonpayable"
  >;

  updateWorkerReputation: TypedContractMethod<
    [worker: AddressLike, successful: boolean],
    [void],
    "nonpayable"
  >;

  updateWorkerReputationWithCategory: TypedContractMethod<
    [worker: AddressLike, category: BigNumberish, successful: boolean],
    [void],
    "nonpayable"
  >;

  verificationContractAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BADGE_SUCCESS_RATE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BADGE_TASK_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HIGH_REPUTATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_DECREASE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_INCREASE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REPUTATION_MULTIPLIER_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCategoryStats"
  ): TypedContractMethod<
    [user: AddressLike, category: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        successCount: bigint;
        totalCount: bigint;
        hasBadge: boolean;
        successRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputationData"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        tasksCompleted: bigint;
        tasksRejected: bigint;
        verificationsPerformed: bigint;
        accurateVerifications: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputationMultiplier"
  ): TypedContractMethod<
    [user: AddressLike, category: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputationScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSuccessRate"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVerificationAccuracy"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasCategoryBadge"
  ): TypedContractMethod<
    [user: AddressLike, category: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPriorityAccess"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initializeReputation"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTaskManager"
  ): TypedContractMethod<[_taskManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationContract"
  ): TypedContractMethod<
    [_verificationContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskManagerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVerifierReputation"
  ): TypedContractMethod<
    [verifier: AddressLike, accurateVote: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWorkerReputation"
  ): TypedContractMethod<
    [worker: AddressLike, successful: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWorkerReputationWithCategory"
  ): TypedContractMethod<
    [worker: AddressLike, category: BigNumberish, successful: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verificationContractAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CategoryBadgeAwarded"
  ): TypedContractEvent<
    CategoryBadgeAwardedEvent.InputTuple,
    CategoryBadgeAwardedEvent.OutputTuple,
    CategoryBadgeAwardedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationInitialized"
  ): TypedContractEvent<
    ReputationInitializedEvent.InputTuple,
    ReputationInitializedEvent.OutputTuple,
    ReputationInitializedEvent.OutputObject
  >;
  getEvent(
    key: "TaskManagerUpdated"
  ): TypedContractEvent<
    TaskManagerUpdatedEvent.InputTuple,
    TaskManagerUpdatedEvent.OutputTuple,
    TaskManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationContractUpdated"
  ): TypedContractEvent<
    VerificationContractUpdatedEvent.InputTuple,
    VerificationContractUpdatedEvent.OutputTuple,
    VerificationContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierReputationUpdated"
  ): TypedContractEvent<
    VerifierReputationUpdatedEvent.InputTuple,
    VerifierReputationUpdatedEvent.OutputTuple,
    VerifierReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WorkerReputationUpdated"
  ): TypedContractEvent<
    WorkerReputationUpdatedEvent.InputTuple,
    WorkerReputationUpdatedEvent.OutputTuple,
    WorkerReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "CategoryBadgeAwarded(address,uint8)": TypedContractEvent<
      CategoryBadgeAwardedEvent.InputTuple,
      CategoryBadgeAwardedEvent.OutputTuple,
      CategoryBadgeAwardedEvent.OutputObject
    >;
    CategoryBadgeAwarded: TypedContractEvent<
      CategoryBadgeAwardedEvent.InputTuple,
      CategoryBadgeAwardedEvent.OutputTuple,
      CategoryBadgeAwardedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationInitialized(address,uint256)": TypedContractEvent<
      ReputationInitializedEvent.InputTuple,
      ReputationInitializedEvent.OutputTuple,
      ReputationInitializedEvent.OutputObject
    >;
    ReputationInitialized: TypedContractEvent<
      ReputationInitializedEvent.InputTuple,
      ReputationInitializedEvent.OutputTuple,
      ReputationInitializedEvent.OutputObject
    >;

    "TaskManagerUpdated(address)": TypedContractEvent<
      TaskManagerUpdatedEvent.InputTuple,
      TaskManagerUpdatedEvent.OutputTuple,
      TaskManagerUpdatedEvent.OutputObject
    >;
    TaskManagerUpdated: TypedContractEvent<
      TaskManagerUpdatedEvent.InputTuple,
      TaskManagerUpdatedEvent.OutputTuple,
      TaskManagerUpdatedEvent.OutputObject
    >;

    "VerificationContractUpdated(address)": TypedContractEvent<
      VerificationContractUpdatedEvent.InputTuple,
      VerificationContractUpdatedEvent.OutputTuple,
      VerificationContractUpdatedEvent.OutputObject
    >;
    VerificationContractUpdated: TypedContractEvent<
      VerificationContractUpdatedEvent.InputTuple,
      VerificationContractUpdatedEvent.OutputTuple,
      VerificationContractUpdatedEvent.OutputObject
    >;

    "VerifierReputationUpdated(address,bool,uint256)": TypedContractEvent<
      VerifierReputationUpdatedEvent.InputTuple,
      VerifierReputationUpdatedEvent.OutputTuple,
      VerifierReputationUpdatedEvent.OutputObject
    >;
    VerifierReputationUpdated: TypedContractEvent<
      VerifierReputationUpdatedEvent.InputTuple,
      VerifierReputationUpdatedEvent.OutputTuple,
      VerifierReputationUpdatedEvent.OutputObject
    >;

    "WorkerReputationUpdated(address,bool,uint256)": TypedContractEvent<
      WorkerReputationUpdatedEvent.InputTuple,
      WorkerReputationUpdatedEvent.OutputTuple,
      WorkerReputationUpdatedEvent.OutputObject
    >;
    WorkerReputationUpdated: TypedContractEvent<
      WorkerReputationUpdatedEvent.InputTuple,
      WorkerReputationUpdatedEvent.OutputTuple,
      WorkerReputationUpdatedEvent.OutputObject
    >;
  };
}
