/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TaskManager {
  export type LocationStruct = {
    latitude: BigNumberish;
    longitude: BigNumberish;
    radius: BigNumberish;
  };

  export type LocationStructOutput = [
    latitude: bigint,
    longitude: bigint,
    radius: bigint
  ] & { latitude: bigint; longitude: bigint; radius: bigint };

  export type TaskRequirementsStruct = {
    photoCount: BigNumberish;
    requiresLocation: boolean;
    minReputation: BigNumberish;
    requiredBadge: BigNumberish;
  };

  export type TaskRequirementsStructOutput = [
    photoCount: bigint,
    requiresLocation: boolean,
    minReputation: bigint,
    requiredBadge: bigint
  ] & {
    photoCount: bigint;
    requiresLocation: boolean;
    minReputation: bigint;
    requiredBadge: bigint;
  };

  export type TaskStruct = {
    id: BigNumberish;
    creator: AddressLike;
    description: string;
    category: BigNumberish;
    bountyAmount: BigNumberish;
    maxWorkers: BigNumberish;
    location: TaskManager.LocationStruct;
    deadline: BigNumberish;
    status: BigNumberish;
    requirements: TaskManager.TaskRequirementsStruct;
    submissionCount: BigNumberish;
    verifiedCount: BigNumberish;
    createdAt: BigNumberish;
  };

  export type TaskStructOutput = [
    id: bigint,
    creator: string,
    description: string,
    category: bigint,
    bountyAmount: bigint,
    maxWorkers: bigint,
    location: TaskManager.LocationStructOutput,
    deadline: bigint,
    status: bigint,
    requirements: TaskManager.TaskRequirementsStructOutput,
    submissionCount: bigint,
    verifiedCount: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    creator: string;
    description: string;
    category: bigint;
    bountyAmount: bigint;
    maxWorkers: bigint;
    location: TaskManager.LocationStructOutput;
    deadline: bigint;
    status: bigint;
    requirements: TaskManager.TaskRequirementsStructOutput;
    submissionCount: bigint;
    verifiedCount: bigint;
    createdAt: bigint;
  };
}

export interface TaskManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_ACTIVE_TASKS_PER_WORKER"
      | "MINIMUM_BOUNTY"
      | "TASK_COMPLETION_TIMEOUT"
      | "claimTask"
      | "createTask"
      | "expireTask"
      | "getTask"
      | "getTaskWorkers"
      | "getWorkerActiveTasks"
      | "hasWorkerClaimed"
      | "owner"
      | "renounceOwnership"
      | "submitTaskCompletion"
      | "taskClaims"
      | "taskWorkers"
      | "tasks"
      | "transferOwnership"
      | "workerActiveTasks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "TaskClaimed"
      | "TaskCreated"
      | "TaskExpired"
      | "TaskSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_ACTIVE_TASKS_PER_WORKER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_BOUNTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TASK_COMPLETION_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      TaskManager.LocationStruct,
      BigNumberish,
      TaskManager.TaskRequirementsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "expireTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskWorkers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerActiveTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWorkerClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitTaskCompletion",
    values: [BigNumberish, string, TaskManager.LocationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "taskClaims",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskWorkers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "workerActiveTasks",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_ACTIVE_TASKS_PER_WORKER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_BOUNTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TASK_COMPLETION_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expireTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerActiveTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasWorkerClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTaskCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskClaims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "taskWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workerActiveTasks",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskClaimedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    worker: AddressLike,
    claimedAt: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, worker: string, claimedAt: bigint];
  export interface OutputObject {
    taskId: bigint;
    worker: string;
    claimedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    creator: AddressLike,
    category: BigNumberish,
    bountyAmount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    creator: string,
    category: bigint,
    bountyAmount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    creator: string;
    category: bigint;
    bountyAmount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskExpiredEvent {
  export type InputTuple = [taskId: BigNumberish, expiredAt: BigNumberish];
  export type OutputTuple = [taskId: bigint, expiredAt: bigint];
  export interface OutputObject {
    taskId: bigint;
    expiredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSubmittedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    worker: AddressLike,
    ipfsHash: string,
    submittedAt: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    worker: string,
    ipfsHash: string,
    submittedAt: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    worker: string;
    ipfsHash: string;
    submittedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskManager extends BaseContract {
  connect(runner?: ContractRunner | null): TaskManager;
  waitForDeployment(): Promise<this>;

  interface: TaskManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_ACTIVE_TASKS_PER_WORKER: TypedContractMethod<[], [bigint], "view">;

  MINIMUM_BOUNTY: TypedContractMethod<[], [bigint], "view">;

  TASK_COMPLETION_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  claimTask: TypedContractMethod<
    [taskId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      description: string,
      category: BigNumberish,
      bountyAmount: BigNumberish,
      maxWorkers: BigNumberish,
      location: TaskManager.LocationStruct,
      deadline: BigNumberish,
      requirements: TaskManager.TaskRequirementsStruct
    ],
    [bigint],
    "payable"
  >;

  expireTask: TypedContractMethod<
    [taskId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [TaskManager.TaskStructOutput],
    "view"
  >;

  getTaskWorkers: TypedContractMethod<
    [taskId: BigNumberish],
    [string[]],
    "view"
  >;

  getWorkerActiveTasks: TypedContractMethod<
    [worker: AddressLike],
    [bigint[]],
    "view"
  >;

  hasWorkerClaimed: TypedContractMethod<
    [taskId: BigNumberish, worker: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitTaskCompletion: TypedContractMethod<
    [
      taskId: BigNumberish,
      ipfsHash: string,
      submissionLocation: TaskManager.LocationStruct
    ],
    [bigint],
    "nonpayable"
  >;

  taskClaims: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean] & {
        worker: string;
        claimedAt: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;

  taskWorkers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        TaskManager.LocationStructOutput,
        bigint,
        bigint,
        TaskManager.TaskRequirementsStructOutput,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        description: string;
        category: bigint;
        bountyAmount: bigint;
        maxWorkers: bigint;
        location: TaskManager.LocationStructOutput;
        deadline: bigint;
        status: bigint;
        requirements: TaskManager.TaskRequirementsStructOutput;
        submissionCount: bigint;
        verifiedCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  workerActiveTasks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_ACTIVE_TASKS_PER_WORKER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMUM_BOUNTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TASK_COMPLETION_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimTask"
  ): TypedContractMethod<[taskId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      description: string,
      category: BigNumberish,
      bountyAmount: BigNumberish,
      maxWorkers: BigNumberish,
      location: TaskManager.LocationStruct,
      deadline: BigNumberish,
      requirements: TaskManager.TaskRequirementsStruct
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "expireTask"
  ): TypedContractMethod<[taskId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [TaskManager.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskWorkers"
  ): TypedContractMethod<[taskId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getWorkerActiveTasks"
  ): TypedContractMethod<[worker: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasWorkerClaimed"
  ): TypedContractMethod<
    [taskId: BigNumberish, worker: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitTaskCompletion"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      ipfsHash: string,
      submissionLocation: TaskManager.LocationStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskClaims"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean] & {
        worker: string;
        claimedAt: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "taskWorkers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        TaskManager.LocationStructOutput,
        bigint,
        bigint,
        TaskManager.TaskRequirementsStructOutput,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creator: string;
        description: string;
        category: bigint;
        bountyAmount: bigint;
        maxWorkers: bigint;
        location: TaskManager.LocationStructOutput;
        deadline: bigint;
        status: bigint;
        requirements: TaskManager.TaskRequirementsStructOutput;
        submissionCount: bigint;
        verifiedCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "workerActiveTasks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskClaimed"
  ): TypedContractEvent<
    TaskClaimedEvent.InputTuple,
    TaskClaimedEvent.OutputTuple,
    TaskClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskExpired"
  ): TypedContractEvent<
    TaskExpiredEvent.InputTuple,
    TaskExpiredEvent.OutputTuple,
    TaskExpiredEvent.OutputObject
  >;
  getEvent(
    key: "TaskSubmitted"
  ): TypedContractEvent<
    TaskSubmittedEvent.InputTuple,
    TaskSubmittedEvent.OutputTuple,
    TaskSubmittedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskClaimed(uint256,address,uint256)": TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;
    TaskClaimed: TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;

    "TaskCreated(uint256,address,uint8,uint256,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskExpired(uint256,uint256)": TypedContractEvent<
      TaskExpiredEvent.InputTuple,
      TaskExpiredEvent.OutputTuple,
      TaskExpiredEvent.OutputObject
    >;
    TaskExpired: TypedContractEvent<
      TaskExpiredEvent.InputTuple,
      TaskExpiredEvent.OutputTuple,
      TaskExpiredEvent.OutputObject
    >;

    "TaskSubmitted(uint256,address,string,uint256)": TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;
    TaskSubmitted: TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;
  };
}
