/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBountyPool,
  IBountyPoolInterface,
} from "../../../contracts/VerificationContract.sol/IBountyPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "distributeReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBountyPool__factory {
  static readonly abi = _abi;
  static createInterface(): IBountyPoolInterface {
    return new Interface(_abi) as IBountyPoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBountyPool {
    return new Contract(address, _abi, runner) as unknown as IBountyPool;
  }
}
