/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAntiFraud__factory } from "./IAntiFraud__factory";
export { TaskManager__factory } from "./TaskManager__factory";
