/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BountyPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "EXPIRED_TASK_FEE_PERCENTAGE"
      | "PLATFORM_FEE_PERCENTAGE"
      | "accumulatedFees"
      | "calculateExpiredTaskFee"
      | "calculatePlatformFee"
      | "depositBounty"
      | "distributeReward"
      | "getAccumulatedFees"
      | "getTaskBounty"
      | "owner"
      | "refundBounty"
      | "renounceOwnership"
      | "setTaskManager"
      | "setVerificationContract"
      | "taskBounties"
      | "taskManagerAddress"
      | "transferOwnership"
      | "verificationContractAddress"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyDeposited"
      | "BountyRefunded"
      | "OwnershipTransferred"
      | "PlatformFeesWithdrawn"
      | "RewardDistributed"
      | "TaskManagerUpdated"
      | "VerificationContractUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXPIRED_TASK_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateExpiredTaskFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundBounty",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTaskManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskBounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taskManagerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXPIRED_TASK_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateExpiredTaskFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaskBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTaskManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskBounties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace BountyDepositedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, creator: string, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyRefundedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    creator: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    creator: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeesWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    worker: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    worker: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskManagerUpdatedEvent {
  export type InputTuple = [newTaskManager: AddressLike];
  export type OutputTuple = [newTaskManager: string];
  export interface OutputObject {
    newTaskManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationContractUpdatedEvent {
  export type InputTuple = [newVerificationContract: AddressLike];
  export type OutputTuple = [newVerificationContract: string];
  export interface OutputObject {
    newVerificationContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BountyPool extends BaseContract {
  connect(runner?: ContractRunner | null): BountyPool;
  waitForDeployment(): Promise<this>;

  interface: BountyPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  EXPIRED_TASK_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  accumulatedFees: TypedContractMethod<[], [bigint], "view">;

  calculateExpiredTaskFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  calculatePlatformFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  depositBounty: TypedContractMethod<[taskId: BigNumberish], [void], "payable">;

  distributeReward: TypedContractMethod<
    [taskId: BigNumberish, worker: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAccumulatedFees: TypedContractMethod<[], [bigint], "view">;

  getTaskBounty: TypedContractMethod<[taskId: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refundBounty: TypedContractMethod<
    [taskId: BigNumberish, creator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTaskManager: TypedContractMethod<
    [_taskManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerificationContract: TypedContractMethod<
    [_verificationContract: AddressLike],
    [void],
    "nonpayable"
  >;

  taskBounties: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  taskManagerAddress: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verificationContractAddress: TypedContractMethod<[], [string], "view">;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EXPIRED_TASK_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateExpiredTaskFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePlatformFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositBounty"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<
    [taskId: BigNumberish, worker: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAccumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTaskBounty"
  ): TypedContractMethod<[taskId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundBounty"
  ): TypedContractMethod<
    [taskId: BigNumberish, creator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTaskManager"
  ): TypedContractMethod<[_taskManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationContract"
  ): TypedContractMethod<
    [_verificationContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskBounties"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "taskManagerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationContractAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BountyDeposited"
  ): TypedContractEvent<
    BountyDepositedEvent.InputTuple,
    BountyDepositedEvent.OutputTuple,
    BountyDepositedEvent.OutputObject
  >;
  getEvent(
    key: "BountyRefunded"
  ): TypedContractEvent<
    BountyRefundedEvent.InputTuple,
    BountyRefundedEvent.OutputTuple,
    BountyRefundedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeesWithdrawn"
  ): TypedContractEvent<
    PlatformFeesWithdrawnEvent.InputTuple,
    PlatformFeesWithdrawnEvent.OutputTuple,
    PlatformFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "TaskManagerUpdated"
  ): TypedContractEvent<
    TaskManagerUpdatedEvent.InputTuple,
    TaskManagerUpdatedEvent.OutputTuple,
    TaskManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationContractUpdated"
  ): TypedContractEvent<
    VerificationContractUpdatedEvent.InputTuple,
    VerificationContractUpdatedEvent.OutputTuple,
    VerificationContractUpdatedEvent.OutputObject
  >;

  filters: {
    "BountyDeposited(uint256,address,uint256)": TypedContractEvent<
      BountyDepositedEvent.InputTuple,
      BountyDepositedEvent.OutputTuple,
      BountyDepositedEvent.OutputObject
    >;
    BountyDeposited: TypedContractEvent<
      BountyDepositedEvent.InputTuple,
      BountyDepositedEvent.OutputTuple,
      BountyDepositedEvent.OutputObject
    >;

    "BountyRefunded(uint256,address,uint256,uint256)": TypedContractEvent<
      BountyRefundedEvent.InputTuple,
      BountyRefundedEvent.OutputTuple,
      BountyRefundedEvent.OutputObject
    >;
    BountyRefunded: TypedContractEvent<
      BountyRefundedEvent.InputTuple,
      BountyRefundedEvent.OutputTuple,
      BountyRefundedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeesWithdrawn(address,uint256)": TypedContractEvent<
      PlatformFeesWithdrawnEvent.InputTuple,
      PlatformFeesWithdrawnEvent.OutputTuple,
      PlatformFeesWithdrawnEvent.OutputObject
    >;
    PlatformFeesWithdrawn: TypedContractEvent<
      PlatformFeesWithdrawnEvent.InputTuple,
      PlatformFeesWithdrawnEvent.OutputTuple,
      PlatformFeesWithdrawnEvent.OutputObject
    >;

    "RewardDistributed(uint256,address,uint256,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "TaskManagerUpdated(address)": TypedContractEvent<
      TaskManagerUpdatedEvent.InputTuple,
      TaskManagerUpdatedEvent.OutputTuple,
      TaskManagerUpdatedEvent.OutputObject
    >;
    TaskManagerUpdated: TypedContractEvent<
      TaskManagerUpdatedEvent.InputTuple,
      TaskManagerUpdatedEvent.OutputTuple,
      TaskManagerUpdatedEvent.OutputObject
    >;

    "VerificationContractUpdated(address)": TypedContractEvent<
      VerificationContractUpdatedEvent.InputTuple,
      VerificationContractUpdatedEvent.OutputTuple,
      VerificationContractUpdatedEvent.OutputObject
    >;
    VerificationContractUpdated: TypedContractEvent<
      VerificationContractUpdatedEvent.InputTuple,
      VerificationContractUpdatedEvent.OutputTuple,
      VerificationContractUpdatedEvent.OutputObject
    >;
  };
}
