/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VerificationContract {
  export type LocationStruct = {
    latitude: BigNumberish;
    longitude: BigNumberish;
    radius: BigNumberish;
  };

  export type LocationStructOutput = [
    latitude: bigint,
    longitude: bigint,
    radius: bigint
  ] & { latitude: bigint; longitude: bigint; radius: bigint };

  export type SubmissionStruct = {
    id: BigNumberish;
    taskId: BigNumberish;
    worker: AddressLike;
    ipfsHash: string;
    timestamp: BigNumberish;
    location: VerificationContract.LocationStruct;
    status: BigNumberish;
    approvalCount: BigNumberish;
    rejectionCount: BigNumberish;
    totalVotes: BigNumberish;
    bountyAmount: BigNumberish;
    rewardDistributed: boolean;
  };

  export type SubmissionStructOutput = [
    id: bigint,
    taskId: bigint,
    worker: string,
    ipfsHash: string,
    timestamp: bigint,
    location: VerificationContract.LocationStructOutput,
    status: bigint,
    approvalCount: bigint,
    rejectionCount: bigint,
    totalVotes: bigint,
    bountyAmount: bigint,
    rewardDistributed: boolean
  ] & {
    id: bigint;
    taskId: bigint;
    worker: string;
    ipfsHash: string;
    timestamp: bigint;
    location: VerificationContract.LocationStructOutput;
    status: bigint;
    approvalCount: bigint;
    rejectionCount: bigint;
    totalVotes: bigint;
    bountyAmount: bigint;
    rewardDistributed: boolean;
  };

  export type VoteStruct = {
    hasVoted: boolean;
    approved: boolean;
    timestamp: BigNumberish;
    stake: BigNumberish;
  };

  export type VoteStructOutput = [
    hasVoted: boolean,
    approved: boolean,
    timestamp: bigint,
    stake: bigint
  ] & {
    hasVoted: boolean;
    approved: boolean;
    timestamp: bigint;
    stake: bigint;
  };
}

export interface VerificationContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "CONSENSUS_THRESHOLD"
      | "MAX_VERIFIERS"
      | "REWARD_DISTRIBUTION_DELAY"
      | "VERIFICATION_REWARD_PERCENTAGE"
      | "VERIFICATION_STAKE"
      | "antiFraudAddress"
      | "bountyPoolAddress"
      | "consensusReachedAt"
      | "createSubmission"
      | "distributeVerificationRewards"
      | "getSubmission"
      | "getSubmissionVerifiers"
      | "getVote"
      | "hasConsensus"
      | "owner"
      | "renounceOwnership"
      | "reputationContractAddress"
      | "setAntiFraud"
      | "setBountyPool"
      | "setReputationContract"
      | "setTaskManager"
      | "stakeForVerification"
      | "submissionVerifiers"
      | "submissions"
      | "submitVerification"
      | "taskManagerAddress"
      | "transferOwnership"
      | "verificationVotes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsensusReached"
      | "DisputeEscalated"
      | "OwnershipTransferred"
      | "RewardDistributed"
      | "SubmissionCreated"
      | "VerificationRewardsDistributed"
      | "VerificationStaked"
      | "VoteSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONSENSUS_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VERIFIERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_DISTRIBUTION_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFICATION_REWARD_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFICATION_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antiFraudAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bountyPoolAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "consensusReachedAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubmission",
    values: [
      BigNumberish,
      AddressLike,
      string,
      VerificationContract.LocationStruct,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeVerificationRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissionVerifiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasConsensus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAntiFraud",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBountyPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReputationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTaskManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeForVerification",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissionVerifiers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVerification",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "taskManagerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationVotes",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONSENSUS_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VERIFIERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_DISTRIBUTION_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFICATION_REWARD_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFICATION_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antiFraudAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bountyPoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consensusReachedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeVerificationRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissionVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasConsensus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAntiFraud",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBountyPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReputationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTaskManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeForVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissionVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationVotes",
    data: BytesLike
  ): Result;
}

export namespace ConsensusReachedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    status: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: bigint,
    status: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    submissionId: bigint;
    status: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeEscalatedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    currentVotes: BigNumberish
  ];
  export type OutputTuple = [submissionId: bigint, currentVotes: bigint];
  export interface OutputObject {
    submissionId: bigint;
    currentVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: bigint,
    worker: string,
    amount: bigint
  ];
  export interface OutputObject {
    submissionId: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionCreatedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    taskId: BigNumberish,
    worker: AddressLike,
    ipfsHash: string
  ];
  export type OutputTuple = [
    submissionId: bigint,
    taskId: bigint,
    worker: string,
    ipfsHash: string
  ];
  export interface OutputObject {
    submissionId: bigint;
    taskId: bigint;
    worker: string;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRewardsDistributedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    totalReward: BigNumberish
  ];
  export type OutputTuple = [submissionId: bigint, totalReward: bigint];
  export interface OutputObject {
    submissionId: bigint;
    totalReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationStakedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    verifier: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: bigint,
    verifier: string,
    amount: bigint
  ];
  export interface OutputObject {
    submissionId: bigint;
    verifier: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteSubmittedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    verifier: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    submissionId: bigint,
    verifier: string,
    approved: boolean
  ];
  export interface OutputObject {
    submissionId: bigint;
    verifier: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerificationContract extends BaseContract {
  connect(runner?: ContractRunner | null): VerificationContract;
  waitForDeployment(): Promise<this>;

  interface: VerificationContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  CONSENSUS_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_VERIFIERS: TypedContractMethod<[], [bigint], "view">;

  REWARD_DISTRIBUTION_DELAY: TypedContractMethod<[], [bigint], "view">;

  VERIFICATION_REWARD_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  VERIFICATION_STAKE: TypedContractMethod<[], [bigint], "view">;

  antiFraudAddress: TypedContractMethod<[], [string], "view">;

  bountyPoolAddress: TypedContractMethod<[], [string], "view">;

  consensusReachedAt: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  createSubmission: TypedContractMethod<
    [
      taskId: BigNumberish,
      worker: AddressLike,
      ipfsHash: string,
      location: VerificationContract.LocationStruct,
      bountyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  distributeVerificationRewards: TypedContractMethod<
    [submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSubmission: TypedContractMethod<
    [submissionId: BigNumberish],
    [VerificationContract.SubmissionStructOutput],
    "view"
  >;

  getSubmissionVerifiers: TypedContractMethod<
    [submissionId: BigNumberish],
    [string[]],
    "view"
  >;

  getVote: TypedContractMethod<
    [submissionId: BigNumberish, verifier: AddressLike],
    [VerificationContract.VoteStructOutput],
    "view"
  >;

  hasConsensus: TypedContractMethod<
    [submissionId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationContractAddress: TypedContractMethod<[], [string], "view">;

  setAntiFraud: TypedContractMethod<
    [_antiFraud: AddressLike],
    [void],
    "nonpayable"
  >;

  setBountyPool: TypedContractMethod<
    [_bountyPool: AddressLike],
    [void],
    "nonpayable"
  >;

  setReputationContract: TypedContractMethod<
    [_reputationContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setTaskManager: TypedContractMethod<
    [_taskManager: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeForVerification: TypedContractMethod<
    [submissionId: BigNumberish],
    [void],
    "payable"
  >;

  submissionVerifiers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  submissions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        VerificationContract.LocationStructOutput,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        taskId: bigint;
        worker: string;
        ipfsHash: string;
        timestamp: bigint;
        location: VerificationContract.LocationStructOutput;
        status: bigint;
        approvalCount: bigint;
        rejectionCount: bigint;
        totalVotes: bigint;
        bountyAmount: bigint;
        rewardDistributed: boolean;
      }
    ],
    "view"
  >;

  submitVerification: TypedContractMethod<
    [submissionId: BigNumberish, approved: boolean, feedback: string],
    [void],
    "nonpayable"
  >;

  taskManagerAddress: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verificationVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        hasVoted: boolean;
        approved: boolean;
        timestamp: bigint;
        stake: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CONSENSUS_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VERIFIERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_DISTRIBUTION_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFICATION_REWARD_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFICATION_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "antiFraudAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bountyPoolAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "consensusReachedAt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createSubmission"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      worker: AddressLike,
      ipfsHash: string,
      location: VerificationContract.LocationStruct,
      bountyAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeVerificationRewards"
  ): TypedContractMethod<[submissionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [submissionId: BigNumberish],
    [VerificationContract.SubmissionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmissionVerifiers"
  ): TypedContractMethod<[submissionId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [submissionId: BigNumberish, verifier: AddressLike],
    [VerificationContract.VoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasConsensus"
  ): TypedContractMethod<[submissionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationContractAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAntiFraud"
  ): TypedContractMethod<[_antiFraud: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBountyPool"
  ): TypedContractMethod<[_bountyPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReputationContract"
  ): TypedContractMethod<
    [_reputationContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTaskManager"
  ): TypedContractMethod<[_taskManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeForVerification"
  ): TypedContractMethod<[submissionId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "submissionVerifiers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        VerificationContract.LocationStructOutput,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        taskId: bigint;
        worker: string;
        ipfsHash: string;
        timestamp: bigint;
        location: VerificationContract.LocationStructOutput;
        status: bigint;
        approvalCount: bigint;
        rejectionCount: bigint;
        totalVotes: bigint;
        bountyAmount: bigint;
        rewardDistributed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitVerification"
  ): TypedContractMethod<
    [submissionId: BigNumberish, approved: boolean, feedback: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskManagerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, boolean, bigint, bigint] & {
        hasVoted: boolean;
        approved: boolean;
        timestamp: bigint;
        stake: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ConsensusReached"
  ): TypedContractEvent<
    ConsensusReachedEvent.InputTuple,
    ConsensusReachedEvent.OutputTuple,
    ConsensusReachedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeEscalated"
  ): TypedContractEvent<
    DisputeEscalatedEvent.InputTuple,
    DisputeEscalatedEvent.OutputTuple,
    DisputeEscalatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionCreated"
  ): TypedContractEvent<
    SubmissionCreatedEvent.InputTuple,
    SubmissionCreatedEvent.OutputTuple,
    SubmissionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRewardsDistributed"
  ): TypedContractEvent<
    VerificationRewardsDistributedEvent.InputTuple,
    VerificationRewardsDistributedEvent.OutputTuple,
    VerificationRewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationStaked"
  ): TypedContractEvent<
    VerificationStakedEvent.InputTuple,
    VerificationStakedEvent.OutputTuple,
    VerificationStakedEvent.OutputObject
  >;
  getEvent(
    key: "VoteSubmitted"
  ): TypedContractEvent<
    VoteSubmittedEvent.InputTuple,
    VoteSubmittedEvent.OutputTuple,
    VoteSubmittedEvent.OutputObject
  >;

  filters: {
    "ConsensusReached(uint256,uint8,uint256)": TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;
    ConsensusReached: TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;

    "DisputeEscalated(uint256,uint256)": TypedContractEvent<
      DisputeEscalatedEvent.InputTuple,
      DisputeEscalatedEvent.OutputTuple,
      DisputeEscalatedEvent.OutputObject
    >;
    DisputeEscalated: TypedContractEvent<
      DisputeEscalatedEvent.InputTuple,
      DisputeEscalatedEvent.OutputTuple,
      DisputeEscalatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardDistributed(uint256,address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "SubmissionCreated(uint256,uint256,address,string)": TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
    SubmissionCreated: TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;

    "VerificationRewardsDistributed(uint256,uint256)": TypedContractEvent<
      VerificationRewardsDistributedEvent.InputTuple,
      VerificationRewardsDistributedEvent.OutputTuple,
      VerificationRewardsDistributedEvent.OutputObject
    >;
    VerificationRewardsDistributed: TypedContractEvent<
      VerificationRewardsDistributedEvent.InputTuple,
      VerificationRewardsDistributedEvent.OutputTuple,
      VerificationRewardsDistributedEvent.OutputObject
    >;

    "VerificationStaked(uint256,address,uint256)": TypedContractEvent<
      VerificationStakedEvent.InputTuple,
      VerificationStakedEvent.OutputTuple,
      VerificationStakedEvent.OutputObject
    >;
    VerificationStaked: TypedContractEvent<
      VerificationStakedEvent.InputTuple,
      VerificationStakedEvent.OutputTuple,
      VerificationStakedEvent.OutputObject
    >;

    "VoteSubmitted(uint256,address,bool)": TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;
    VoteSubmitted: TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;
  };
}
