/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAntiFraud,
  IAntiFraudInterface,
} from "../../../contracts/VerificationContract.sol/IAntiFraud";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "forfeitStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAntiFraud__factory {
  static readonly abi = _abi;
  static createInterface(): IAntiFraudInterface {
    return new Interface(_abi) as IAntiFraudInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAntiFraud {
    return new Contract(address, _abi, runner) as unknown as IAntiFraud;
  }
}
