/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationContract,
  IReputationContractInterface,
} from "../../../contracts/VerificationContract.sol/IReputationContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "verifier",
        type: "address",
      },
      {
        internalType: "bool",
        name: "accurateVote",
        type: "bool",
      },
    ],
    name: "updateVerifierReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "worker",
        type: "address",
      },
      {
        internalType: "bool",
        name: "successful",
        type: "bool",
      },
    ],
    name: "updateWorkerReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputationContract__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationContractInterface {
    return new Interface(_abi) as IReputationContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationContract {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IReputationContract;
  }
}
