/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AntiFraud {
  export type SubmissionRecordStruct = {
    timestamp: BigNumberish;
    imageHash: string;
    metadataHash: BytesLike;
  };

  export type SubmissionRecordStructOutput = [
    timestamp: bigint,
    imageHash: string,
    metadataHash: string
  ] & { timestamp: bigint; imageHash: string; metadataHash: string };
}

export interface AntiFraudInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DUPLICATE_SIMILARITY_THRESHOLD"
      | "MAX_SUBMISSIONS_PER_DAY"
      | "ONE_DAY"
      | "blacklistWorker"
      | "blacklistedWorkers"
      | "checkAndRecordSubmission"
      | "checkImageSimilarity"
      | "forfeitStake"
      | "getImageHashWorker"
      | "getTodaySubmissionCount"
      | "getWorkerSubmissions"
      | "imageHashToWorker"
      | "isImageHashUsed"
      | "isWorkerBlacklisted"
      | "owner"
      | "renounceOwnership"
      | "setTaskManager"
      | "setVerificationContract"
      | "taskManagerAddress"
      | "transferOwnership"
      | "unblacklistWorker"
      | "usedImageHashes"
      | "validateTimestamp"
      | "verificationContractAddress"
      | "workerDailySubmissions"
      | "workerStakes"
      | "workerSubmissions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DuplicateDetected"
      | "OwnershipTransferred"
      | "RateLimitExceeded"
      | "StakeForfeited"
      | "SubmissionRecorded"
      | "WorkerBlacklisted"
      | "WorkerUnblacklisted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DUPLICATE_SIMILARITY_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUBMISSIONS_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ONE_DAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blacklistWorker",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedWorkers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAndRecordSubmission",
    values: [AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkImageSimilarity",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forfeitStake",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getImageHashWorker",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTodaySubmissionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerSubmissions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "imageHashToWorker",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isImageHashUsed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isWorkerBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTaskManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskManagerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblacklistWorker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedImageHashes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTimestamp",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "workerDailySubmissions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "workerStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "workerSubmissions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DUPLICATE_SIMILARITY_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SUBMISSIONS_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ONE_DAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAndRecordSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkImageSimilarity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forfeitStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImageHashWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTodaySubmissionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "imageHashToWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isImageHashUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWorkerBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTaskManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblacklistWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedImageHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workerDailySubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workerStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workerSubmissions",
    data: BytesLike
  ): Result;
}

export namespace DuplicateDetectedEvent {
  export type InputTuple = [
    worker: AddressLike,
    imageHash: string,
    originalWorker: AddressLike
  ];
  export type OutputTuple = [
    worker: string,
    imageHash: string,
    originalWorker: string
  ];
  export interface OutputObject {
    worker: string;
    imageHash: string;
    originalWorker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitExceededEvent {
  export type InputTuple = [
    worker: AddressLike,
    currentCount: BigNumberish,
    maxAllowed: BigNumberish
  ];
  export type OutputTuple = [
    worker: string,
    currentCount: bigint,
    maxAllowed: bigint
  ];
  export interface OutputObject {
    worker: string;
    currentCount: bigint;
    maxAllowed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeForfeitedEvent {
  export type InputTuple = [
    worker: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [worker: string, amount: bigint, reason: string];
  export interface OutputObject {
    worker: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionRecordedEvent {
  export type InputTuple = [
    worker: AddressLike,
    taskId: BigNumberish,
    imageHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    worker: string,
    taskId: bigint,
    imageHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    worker: string;
    taskId: bigint;
    imageHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkerBlacklistedEvent {
  export type InputTuple = [worker: AddressLike, reason: string];
  export type OutputTuple = [worker: string, reason: string];
  export interface OutputObject {
    worker: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkerUnblacklistedEvent {
  export type InputTuple = [worker: AddressLike];
  export type OutputTuple = [worker: string];
  export interface OutputObject {
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AntiFraud extends BaseContract {
  connect(runner?: ContractRunner | null): AntiFraud;
  waitForDeployment(): Promise<this>;

  interface: AntiFraudInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DUPLICATE_SIMILARITY_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_SUBMISSIONS_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  ONE_DAY: TypedContractMethod<[], [bigint], "view">;

  blacklistWorker: TypedContractMethod<
    [worker: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  blacklistedWorkers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  checkAndRecordSubmission: TypedContractMethod<
    [
      worker: AddressLike,
      taskId: BigNumberish,
      imageHash: string,
      metadataHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  checkImageSimilarity: TypedContractMethod<
    [imageHash: string, similarityThreshold: BigNumberish],
    [[boolean, string] & { isSimilar: boolean; originalWorker: string }],
    "view"
  >;

  forfeitStake: TypedContractMethod<
    [worker: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  getImageHashWorker: TypedContractMethod<
    [imageHash: string],
    [string],
    "view"
  >;

  getTodaySubmissionCount: TypedContractMethod<
    [worker: AddressLike],
    [bigint],
    "view"
  >;

  getWorkerSubmissions: TypedContractMethod<
    [worker: AddressLike],
    [AntiFraud.SubmissionRecordStructOutput[]],
    "view"
  >;

  imageHashToWorker: TypedContractMethod<[arg0: string], [string], "view">;

  isImageHashUsed: TypedContractMethod<[imageHash: string], [boolean], "view">;

  isWorkerBlacklisted: TypedContractMethod<
    [worker: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTaskManager: TypedContractMethod<
    [_taskManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerificationContract: TypedContractMethod<
    [_verificationContract: AddressLike],
    [void],
    "nonpayable"
  >;

  taskManagerAddress: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unblacklistWorker: TypedContractMethod<
    [worker: AddressLike],
    [void],
    "nonpayable"
  >;

  usedImageHashes: TypedContractMethod<[arg0: string], [boolean], "view">;

  validateTimestamp: TypedContractMethod<
    [timestamp: BigNumberish, maxAge: BigNumberish],
    [boolean],
    "view"
  >;

  verificationContractAddress: TypedContractMethod<[], [string], "view">;

  workerDailySubmissions: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { date: bigint; count: bigint }],
    "view"
  >;

  workerStakes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  workerSubmissions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, string] & {
        timestamp: bigint;
        imageHash: string;
        metadataHash: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DUPLICATE_SIMILARITY_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUBMISSIONS_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ONE_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blacklistWorker"
  ): TypedContractMethod<
    [worker: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklistedWorkers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkAndRecordSubmission"
  ): TypedContractMethod<
    [
      worker: AddressLike,
      taskId: BigNumberish,
      imageHash: string,
      metadataHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkImageSimilarity"
  ): TypedContractMethod<
    [imageHash: string, similarityThreshold: BigNumberish],
    [[boolean, string] & { isSimilar: boolean; originalWorker: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "forfeitStake"
  ): TypedContractMethod<
    [worker: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getImageHashWorker"
  ): TypedContractMethod<[imageHash: string], [string], "view">;
  getFunction(
    nameOrSignature: "getTodaySubmissionCount"
  ): TypedContractMethod<[worker: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWorkerSubmissions"
  ): TypedContractMethod<
    [worker: AddressLike],
    [AntiFraud.SubmissionRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "imageHashToWorker"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "isImageHashUsed"
  ): TypedContractMethod<[imageHash: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWorkerBlacklisted"
  ): TypedContractMethod<[worker: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTaskManager"
  ): TypedContractMethod<[_taskManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationContract"
  ): TypedContractMethod<
    [_verificationContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskManagerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unblacklistWorker"
  ): TypedContractMethod<[worker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedImageHashes"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "validateTimestamp"
  ): TypedContractMethod<
    [timestamp: BigNumberish, maxAge: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verificationContractAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "workerDailySubmissions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { date: bigint; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "workerStakes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "workerSubmissions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, string] & {
        timestamp: bigint;
        imageHash: string;
        metadataHash: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DuplicateDetected"
  ): TypedContractEvent<
    DuplicateDetectedEvent.InputTuple,
    DuplicateDetectedEvent.OutputTuple,
    DuplicateDetectedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitExceeded"
  ): TypedContractEvent<
    RateLimitExceededEvent.InputTuple,
    RateLimitExceededEvent.OutputTuple,
    RateLimitExceededEvent.OutputObject
  >;
  getEvent(
    key: "StakeForfeited"
  ): TypedContractEvent<
    StakeForfeitedEvent.InputTuple,
    StakeForfeitedEvent.OutputTuple,
    StakeForfeitedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionRecorded"
  ): TypedContractEvent<
    SubmissionRecordedEvent.InputTuple,
    SubmissionRecordedEvent.OutputTuple,
    SubmissionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "WorkerBlacklisted"
  ): TypedContractEvent<
    WorkerBlacklistedEvent.InputTuple,
    WorkerBlacklistedEvent.OutputTuple,
    WorkerBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "WorkerUnblacklisted"
  ): TypedContractEvent<
    WorkerUnblacklistedEvent.InputTuple,
    WorkerUnblacklistedEvent.OutputTuple,
    WorkerUnblacklistedEvent.OutputObject
  >;

  filters: {
    "DuplicateDetected(address,string,address)": TypedContractEvent<
      DuplicateDetectedEvent.InputTuple,
      DuplicateDetectedEvent.OutputTuple,
      DuplicateDetectedEvent.OutputObject
    >;
    DuplicateDetected: TypedContractEvent<
      DuplicateDetectedEvent.InputTuple,
      DuplicateDetectedEvent.OutputTuple,
      DuplicateDetectedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RateLimitExceeded(address,uint256,uint256)": TypedContractEvent<
      RateLimitExceededEvent.InputTuple,
      RateLimitExceededEvent.OutputTuple,
      RateLimitExceededEvent.OutputObject
    >;
    RateLimitExceeded: TypedContractEvent<
      RateLimitExceededEvent.InputTuple,
      RateLimitExceededEvent.OutputTuple,
      RateLimitExceededEvent.OutputObject
    >;

    "StakeForfeited(address,uint256,string)": TypedContractEvent<
      StakeForfeitedEvent.InputTuple,
      StakeForfeitedEvent.OutputTuple,
      StakeForfeitedEvent.OutputObject
    >;
    StakeForfeited: TypedContractEvent<
      StakeForfeitedEvent.InputTuple,
      StakeForfeitedEvent.OutputTuple,
      StakeForfeitedEvent.OutputObject
    >;

    "SubmissionRecorded(address,uint256,string,uint256)": TypedContractEvent<
      SubmissionRecordedEvent.InputTuple,
      SubmissionRecordedEvent.OutputTuple,
      SubmissionRecordedEvent.OutputObject
    >;
    SubmissionRecorded: TypedContractEvent<
      SubmissionRecordedEvent.InputTuple,
      SubmissionRecordedEvent.OutputTuple,
      SubmissionRecordedEvent.OutputObject
    >;

    "WorkerBlacklisted(address,string)": TypedContractEvent<
      WorkerBlacklistedEvent.InputTuple,
      WorkerBlacklistedEvent.OutputTuple,
      WorkerBlacklistedEvent.OutputObject
    >;
    WorkerBlacklisted: TypedContractEvent<
      WorkerBlacklistedEvent.InputTuple,
      WorkerBlacklistedEvent.OutputTuple,
      WorkerBlacklistedEvent.OutputObject
    >;

    "WorkerUnblacklisted(address)": TypedContractEvent<
      WorkerUnblacklistedEvent.InputTuple,
      WorkerUnblacklistedEvent.OutputTuple,
      WorkerUnblacklistedEvent.OutputObject
    >;
    WorkerUnblacklisted: TypedContractEvent<
      WorkerUnblacklistedEvent.InputTuple,
      WorkerUnblacklistedEvent.OutputTuple,
      WorkerUnblacklistedEvent.OutputObject
    >;
  };
}
