/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "AntiFraud",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AntiFraud__factory>;
    getContractFactory(
      name: "BountyPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BountyPool__factory>;
    getContractFactory(
      name: "ReputationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReputationContract__factory>;
    getContractFactory(
      name: "IAntiFraud",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAntiFraud__factory>;
    getContractFactory(
      name: "TaskManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TaskManager__factory>;
    getContractFactory(
      name: "IAntiFraud",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAntiFraud__factory>;
    getContractFactory(
      name: "IBountyPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBountyPool__factory>;
    getContractFactory(
      name: "IReputationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReputationContract__factory>;
    getContractFactory(
      name: "VerificationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VerificationContract__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "AntiFraud",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AntiFraud>;
    getContractAt(
      name: "BountyPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BountyPool>;
    getContractAt(
      name: "ReputationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReputationContract>;
    getContractAt(
      name: "IAntiFraud",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAntiFraud>;
    getContractAt(
      name: "TaskManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TaskManager>;
    getContractAt(
      name: "IAntiFraud",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAntiFraud>;
    getContractAt(
      name: "IBountyPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBountyPool>;
    getContractAt(
      name: "IReputationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReputationContract>;
    getContractAt(
      name: "VerificationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VerificationContract>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "AntiFraud",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AntiFraud>;
    deployContract(
      name: "BountyPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BountyPool>;
    deployContract(
      name: "ReputationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationContract>;
    deployContract(
      name: "IAntiFraud",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAntiFraud>;
    deployContract(
      name: "TaskManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TaskManager>;
    deployContract(
      name: "IAntiFraud",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAntiFraud>;
    deployContract(
      name: "IBountyPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBountyPool>;
    deployContract(
      name: "IReputationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReputationContract>;
    deployContract(
      name: "VerificationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerificationContract>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "AntiFraud",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AntiFraud>;
    deployContract(
      name: "BountyPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BountyPool>;
    deployContract(
      name: "ReputationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationContract>;
    deployContract(
      name: "IAntiFraud",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAntiFraud>;
    deployContract(
      name: "TaskManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TaskManager>;
    deployContract(
      name: "IAntiFraud",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAntiFraud>;
    deployContract(
      name: "IBountyPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBountyPool>;
    deployContract(
      name: "IReputationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReputationContract>;
    deployContract(
      name: "VerificationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerificationContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
