/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAntiFraudInterface extends Interface {
  getFunction(nameOrSignature: "checkAndRecordSubmission"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkAndRecordSubmission",
    values: [AddressLike, BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAndRecordSubmission",
    data: BytesLike
  ): Result;
}

export interface IAntiFraud extends BaseContract {
  connect(runner?: ContractRunner | null): IAntiFraud;
  waitForDeployment(): Promise<this>;

  interface: IAntiFraudInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAndRecordSubmission: TypedContractMethod<
    [
      worker: AddressLike,
      taskId: BigNumberish,
      imageHash: string,
      metadataHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAndRecordSubmission"
  ): TypedContractMethod<
    [
      worker: AddressLike,
      taskId: BigNumberish,
      imageHash: string,
      metadataHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
