/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAntiFraud } from "./IAntiFraud";
export type { IBountyPool } from "./IBountyPool";
export type { IReputationContract } from "./IReputationContract";
export type { VerificationContract } from "./VerificationContract";
