/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IReputationContractInterface extends Interface {
  getFunction(
    nameOrSignature: "updateVerifierReputation" | "updateWorkerReputation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "updateVerifierReputation",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWorkerReputation",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "updateVerifierReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWorkerReputation",
    data: BytesLike
  ): Result;
}

export interface IReputationContract extends BaseContract {
  connect(runner?: ContractRunner | null): IReputationContract;
  waitForDeployment(): Promise<this>;

  interface: IReputationContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  updateVerifierReputation: TypedContractMethod<
    [verifier: AddressLike, accurateVote: boolean],
    [void],
    "nonpayable"
  >;

  updateWorkerReputation: TypedContractMethod<
    [worker: AddressLike, successful: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "updateVerifierReputation"
  ): TypedContractMethod<
    [verifier: AddressLike, accurateVote: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWorkerReputation"
  ): TypedContractMethod<
    [worker: AddressLike, successful: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
